spring:
  application:
    name: NutriCheckBackend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:nutricheck
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /api/v1
  port: 8080

nutricheck:
  jwt:
    secret: c9f2b57a978321cc6cfd84d2ec7bb6f87df0541bf738e34d819bc0efaa48f0a8
    expiration: 8640000

calendar:
  test-mode: false